[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
robotics_lib = { version = "0.1.4", registry = "kellnr" }
swift_seller = { path = "../" }
ragnarok = { version = "0.4.11", git = "https://github.com/circled-square/ragnarok.git", tag = "0.4.11" }